-- migration: 20260620_003_synthea_claims
-- layer: bronze  table: unity.bronze.synthea_claims
-- ${PATIENT360_WAREHOUSE_ROOT} is substituted by ddl-apply.sh before beeline -f.
-- rollback: DROP TABLE IF EXISTS unity.bronze.synthea_claims

CREATE TABLE IF NOT EXISTS unity.bronze.synthea_claims (
    Id STRING,
    PATIENTID STRING,
    PROVIDERID STRING,
    PRIMARYPATIENTINSURANCEID STRING,
    SECONDARYPATIENTINSURANCEID STRING,
    DEPARTMENTID STRING,
    PATIENTDEPARTMENTID STRING,
    DIAGNOSIS1 BIGINT,
    DIAGNOSIS2 BIGINT,
    DIAGNOSIS3 BIGINT,
    DIAGNOSIS4 BIGINT,
    DIAGNOSIS5 BIGINT,
    DIAGNOSIS6 BIGINT,
    DIAGNOSIS7 BIGINT,
    DIAGNOSIS8 BIGINT,
    REFERRINGPROVIDERID STRING,
    APPOINTMENTID STRING,
    CURRENTILLNESSDATE TIMESTAMP,
    SERVICEDATE TIMESTAMP,
    SUPERVISINGPROVIDERID STRING,
    STATUS1 STRING,
    STATUS2 STRING,
    STATUSP STRING,
    OUTSTANDING1 DOUBLE,
    OUTSTANDING2 DOUBLE,
    OUTSTANDINGP DOUBLE,
    LASTBILLEDDATE1 TIMESTAMP,
    LASTBILLEDDATE2 TIMESTAMP,
    LASTBILLEDDATEP TIMESTAMP,
    HEALTHCARECLAIMTYPEID1 BIGINT,
    HEALTHCARECLAIMTYPEID2 BIGINT,
    ds DATE NOT NULL,
    _ingested_at TIMESTAMP NOT NULL,
    _source_batch_id STRING NOT NULL,
    _source_file STRING
) USING DELTA
PARTITIONED BY (ds)
LOCATION '${PATIENT360_WAREHOUSE_ROOT}/dev/bronze/synthea_claims'
