"""Source schemas for all 10 Synthea CSV tables."""

from pyspark.sql.types import (
    DateType,
    DecimalType,
    DoubleType,
    IntegerType,
    StringType,
    StructField,
    StructType,
    TimestampType,
)

PATIENTS = StructType([
    StructField("id", StringType(), nullable=False),
    StructField("birthdate", DateType(), nullable=True),
    StructField("deathdate", DateType(), nullable=True),
    StructField("ssn", StringType(), nullable=True),
    StructField("drivers", StringType(), nullable=True),
    StructField("passport", StringType(), nullable=True),
    StructField("prefix", StringType(), nullable=True),
    StructField("first", StringType(), nullable=True),
    StructField("middle", StringType(), nullable=True),
    StructField("last", StringType(), nullable=True),
    StructField("suffix", StringType(), nullable=True),
    StructField("maiden", StringType(), nullable=True),
    StructField("marital", StringType(), nullable=True),
    StructField("race", StringType(), nullable=True),
    StructField("ethnicity", StringType(), nullable=True),
    StructField("gender", StringType(), nullable=True),
    StructField("birthplace", StringType(), nullable=True),
    StructField("address", StringType(), nullable=True),
    StructField("city", StringType(), nullable=True),
    StructField("state", StringType(), nullable=True),
    StructField("county", StringType(), nullable=True),
    StructField("fips", StringType(), nullable=True),
    StructField("zip", StringType(), nullable=True),
    StructField("lat", DoubleType(), nullable=True),
    StructField("lon", DoubleType(), nullable=True),
    StructField("healthcare_expenses", DecimalType(18, 2), nullable=True),
    StructField("healthcare_coverage", DecimalType(18, 2), nullable=True),
    StructField("income", IntegerType(), nullable=True),
])

ENCOUNTERS = StructType([
    StructField("id", StringType(), nullable=False),
    StructField("start", TimestampType(), nullable=True),
    StructField("stop", TimestampType(), nullable=True),
    StructField("patient", StringType(), nullable=True),
    StructField("organization", StringType(), nullable=True),
    StructField("provider", StringType(), nullable=True),
    StructField("payer", StringType(), nullable=True),
    StructField("encounterclass", StringType(), nullable=True),
    StructField("code", StringType(), nullable=True),
    StructField("description", StringType(), nullable=True),
    StructField("base_encounter_cost", DecimalType(18, 2), nullable=True),
    StructField("total_claim_cost", DecimalType(18, 2), nullable=True),
    StructField("payer_coverage", DecimalType(18, 2), nullable=True),
    StructField("reasoncode", StringType(), nullable=True),
    StructField("reasondescription", StringType(), nullable=True),
])

CONDITIONS = StructType([
    StructField("start", DateType(), nullable=True),
    StructField("stop", DateType(), nullable=True),
    StructField("patient", StringType(), nullable=True),
    StructField("encounter", StringType(), nullable=True),
    StructField("code", StringType(), nullable=True),
    StructField("description", StringType(), nullable=True),
])

MEDICATIONS = StructType([
    StructField("start", DateType(), nullable=True),
    StructField("stop", DateType(), nullable=True),
    StructField("patient", StringType(), nullable=True),
    StructField("payer", StringType(), nullable=True),
    StructField("encounter", StringType(), nullable=True),
    StructField("code", StringType(), nullable=True),
    StructField("description", StringType(), nullable=True),
    StructField("base_cost", DecimalType(18, 2), nullable=True),
    StructField("payer_coverage", DecimalType(18, 2), nullable=True),
    StructField("dispenses", IntegerType(), nullable=True),
    StructField("totalcost", DecimalType(18, 2), nullable=True),
    StructField("reasoncode", StringType(), nullable=True),
    StructField("reasondescription", StringType(), nullable=True),
])

OBSERVATIONS = StructType([
    StructField("date", TimestampType(), nullable=True),
    StructField("patient", StringType(), nullable=True),
    StructField("encounter", StringType(), nullable=True),
    StructField("category", StringType(), nullable=True),
    StructField("code", StringType(), nullable=True),
    StructField("description", StringType(), nullable=True),
    StructField("value", StringType(), nullable=True),
    StructField("units", StringType(), nullable=True),
    StructField("type", StringType(), nullable=True),
])

ALLERGIES = StructType([
    StructField("start", DateType(), nullable=True),
    StructField("stop", DateType(), nullable=True),
    StructField("patient", StringType(), nullable=True),
    StructField("encounter", StringType(), nullable=True),
    StructField("code", StringType(), nullable=True),
    StructField("system", StringType(), nullable=True),
    StructField("description", StringType(), nullable=True),
    StructField("type", StringType(), nullable=True),
    StructField("category", StringType(), nullable=True),
    StructField("reaction1", StringType(), nullable=True),
    StructField("description1", StringType(), nullable=True),
    StructField("severity1", StringType(), nullable=True),
    StructField("reaction2", StringType(), nullable=True),
    StructField("description2", StringType(), nullable=True),
    StructField("severity2", StringType(), nullable=True),
])

CLAIMS = StructType([
    StructField("id", StringType(), nullable=False),
    StructField("patientid", StringType(), nullable=True),
    StructField("providerid", StringType(), nullable=True),
    StructField("primarypatientinsuranceid", StringType(), nullable=True),
    StructField("secondarypatientinsuranceid", StringType(), nullable=True),
    StructField("departmentid", StringType(), nullable=True),
    StructField("patientdepartmentid", StringType(), nullable=True),
    StructField("diagnosis1", StringType(), nullable=True),
    StructField("diagnosis2", StringType(), nullable=True),
    StructField("diagnosis3", StringType(), nullable=True),
    StructField("diagnosis4", StringType(), nullable=True),
    StructField("diagnosis5", StringType(), nullable=True),
    StructField("diagnosis6", StringType(), nullable=True),
    StructField("diagnosis7", StringType(), nullable=True),
    StructField("diagnosis8", StringType(), nullable=True),
    StructField("referringproviderid", StringType(), nullable=True),
    StructField("appointmentid", StringType(), nullable=True),
    StructField("currentillnessdate", DateType(), nullable=True),
    StructField("servicedate", DateType(), nullable=True),
    StructField("supervisingproviderid", StringType(), nullable=True),
    StructField("status1", StringType(), nullable=True),
    StructField("status2", StringType(), nullable=True),
    StructField("statusp", StringType(), nullable=True),
    StructField("outstanding1", DecimalType(18, 2), nullable=True),
    StructField("outstanding2", DecimalType(18, 2), nullable=True),
    StructField("outstandingp", DecimalType(18, 2), nullable=True),
    StructField("lastbilleddate1", DateType(), nullable=True),
    StructField("lastbilleddate2", DateType(), nullable=True),
    StructField("lastbilleddatep", DateType(), nullable=True),
    StructField("healthcareclaimtypeid1", IntegerType(), nullable=True),
    StructField("healthcareclaimtypeid2", IntegerType(), nullable=True),
])

ORGANIZATIONS = StructType([
    StructField("id", StringType(), nullable=False),
    StructField("name", StringType(), nullable=True),
    StructField("address", StringType(), nullable=True),
    StructField("city", StringType(), nullable=True),
    StructField("state", StringType(), nullable=True),
    StructField("zip", StringType(), nullable=True),
    StructField("lat", DoubleType(), nullable=True),
    StructField("lon", DoubleType(), nullable=True),
    StructField("phone", StringType(), nullable=True),
    StructField("revenue", DecimalType(18, 2), nullable=True),
    StructField("utilization", IntegerType(), nullable=True),
])

PROVIDERS = StructType([
    StructField("id", StringType(), nullable=False),
    StructField("organization", StringType(), nullable=True),
    StructField("name", StringType(), nullable=True),
    StructField("gender", StringType(), nullable=True),
    StructField("speciality", StringType(), nullable=True),
    StructField("address", StringType(), nullable=True),
    StructField("city", StringType(), nullable=True),
    StructField("state", StringType(), nullable=True),
    StructField("zip", StringType(), nullable=True),
    StructField("lat", DoubleType(), nullable=True),
    StructField("lon", DoubleType(), nullable=True),
    StructField("utilization", IntegerType(), nullable=True),
])

PAYERS = StructType([
    StructField("id", StringType(), nullable=False),
    StructField("name", StringType(), nullable=True),
    StructField("ownership", StringType(), nullable=True),
    StructField("amount_covered", DecimalType(18, 2), nullable=True),
    StructField("amount_uncovered", DecimalType(18, 2), nullable=True),
    StructField("revenue", DecimalType(18, 2), nullable=True),
    StructField("covered_encounters", IntegerType(), nullable=True),
    StructField("uncovered_encounters", IntegerType(), nullable=True),
    StructField("covered_medications", IntegerType(), nullable=True),
    StructField("uncovered_medications", IntegerType(), nullable=True),
    StructField("covered_procedures", IntegerType(), nullable=True),
    StructField("uncovered_procedures", IntegerType(), nullable=True),
    StructField("covered_immunizations", IntegerType(), nullable=True),
    StructField("uncovered_immunizations", IntegerType(), nullable=True),
    StructField("unique_customers", IntegerType(), nullable=True),
    StructField("qols_avg", DoubleType(), nullable=True),
    StructField("member_months", IntegerType(), nullable=True),
])

# Registry — maps table name to (csv filename, schema)
TABLE_REGISTRY: dict[str, tuple[str, StructType]] = {
    "patients":      ("patients.csv",      PATIENTS),
    "encounters":    ("encounters.csv",    ENCOUNTERS),
    "conditions":    ("conditions.csv",    CONDITIONS),
    "medications":   ("medications.csv",   MEDICATIONS),
    "observations":  ("observations.csv",  OBSERVATIONS),
    "allergies":     ("allergies.csv",     ALLERGIES),
    "claims":        ("claims.csv",        CLAIMS),
    "organizations": ("organizations.csv", ORGANIZATIONS),
    "providers":     ("providers.csv",     PROVIDERS),
    "payers":        ("payers.csv",        PAYERS),
}
