"""Spark-submit entry wrapper for gold_recon tasks.

Generated by /developer-plugin:create-gold (reconciliation phase) from the LLD
§4.2 task inventory, rendered from ``inputs/code/v1/scripts/run_layer_entrypoint.py.j2``
(task_type=gold_recon, runner_module=patient_360.gold.reconciliation,
entry_function=main, argv_spec=[--ds, --meta-dq-run-id]). Mirrors
``run_bronze_recon.py``. Do not hand-edit — re-run create-gold to regenerate.

Lifecycle:
  Airflow -> SparkSubmitOperator(application=this_file)
        -> spark-submit run_gold_recon.py --ds ... --meta-dq-run-id ...
        -> patient_360.gold.reconciliation.main(args)
"""

from __future__ import annotations

import argparse
import importlib
import logging
import sys

logger = logging.getLogger(__name__)


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(description="gold_recon entry wrapper")
    p.add_argument(
        "--ds", required=True, help="Logical date YYYY-MM-DD"
    )
    p.add_argument(
        "--meta-dq-run-id",
        required=True,
        help="Airflow run id (typically {{ ts_nodash }})",
    )
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    runner = importlib.import_module("patient_360.gold.reconciliation")
    if not hasattr(runner, "main"):
        raise AttributeError(
            "patient_360.gold.reconciliation has no `main` — regenerate "
            "this wrapper after the runner contract changes."
        )
    return runner.main(args)


if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s"
    )
    sys.exit(main(sys.argv[1:]))
