"""Spark-submit entry wrapper for the Gold build tasks (LLD §4.2 gold_build).

Generated by ``/developer-plugin:create-gold`` Phase 5 from the LLD §4.2 task
inventory + §5.3/§5.4 Gold module map, rendered from
``inputs/code/v1/scripts/run_gold_build.py.snippet``. Do not hand-edit —
re-run create-gold to regenerate.

Lifecycle (one task per Gold consumer table, LLD §4.2 gold_build):
  Airflow -> SparkSubmitOperator(application=this_file,
                application_args=["--table", "<table>", "--ds", ...])
        -> spark-submit run_gold_build.py --table patient_summary --ds ...
        -> patient_360.gold.build_<table>.build(spark, env, ds)

A single parameterised shim covers every Gold builder. ``--table`` selects the
matching ``patient_360.gold.build_<table>`` module; the module's
``build(spark, env, ds)`` is the contract (it owns the Silver reads, inline SE,
and the full-overwrite ``insertInto unity.gold.<table>``). The shim only owns the
SparkSession + argument plumbing so the builder stays import-clean for unit tests
(no SparkSession at import time). Mirrors ``run_silver_transform.py``.
"""

from __future__ import annotations

import argparse
import importlib
import logging
import os
import sys

logger = logging.getLogger(__name__)

# LLD §5.3 / §5.4 Gold consumer tables — the ``--table`` allow-list. Each name
# maps 1:1 to ``patient_360.gold.build_<name>`` and is submitted by the DAG
# ``gold_build`` TaskGroup (LLD §4.2). Kept here so an unknown --table fails
# fast with a clear allow-list instead of an opaque ImportError. Note the DAG
# task ids (build_patient_summary_gold / build_clinical_history_gold /
# build_billing_summary_gold) are NOT derived from these names — the DAG owns
# that table->task_id map (LLD §5.4).
GOLD_TABLES = (
    "patient_summary",
    "patient_clinical_history",
    "patient_billing_summary",
)


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(description="gold build entry wrapper")
    p.add_argument(
        "--table",
        required=True,
        choices=GOLD_TABLES,
        help="Gold consumer table to build (selects build_<table>).",
    )
    p.add_argument(
        "--ds",
        required=True,
        help="Logical date YYYY-MM-DD (build stamp / current-state read date).",
    )
    p.add_argument(
        "--env",
        default=os.environ.get("PATIENT360_ENV", "DEV"),
        help="Deployment env (DEV/TEST/PROD); defaults to PATIENT360_ENV or DEV.",
    )
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    module_name = f"patient_360.gold.build_{args.table}"
    module = importlib.import_module(module_name)
    if not hasattr(module, "build"):
        raise AttributeError(
            f"{module_name} has no `build(spark, env, ds)` — regenerate "
            "this wrapper after the gold builder contract changes."
        )

    # SparkSession built here (NOT in the builder module) so the builder stays
    # importable in pure-Python unit tests. Same Delta+metastore wiring as the
    # silver runner (delta_helpers.build_spark_session).
    from patient_360.utils.delta_helpers import build_spark_session

    spark = build_spark_session(app_name=f"gold_build_{args.table}")
    try:
        module.build(spark, args.env, args.ds)
    finally:
        spark.stop()
    return 0


if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s"
    )
    sys.exit(main(sys.argv[1:]))
