"""Patient 360 hourly medallion pipeline DAG (LLD §4.1, §4.2).

Generated by ``/developer-plugin:create-dag`` for STORY-02-006 from
``chapter-4/outputs/lld/v1/LLD-2026-05-11-patient-360.md``. Hand-edits
are overwritten on the next create-dag run.

Updated 2026-06-22 (update-dag): make ``max_active_tasks`` env-dependent
per LLD §4.1 (DEV=1, STAGING=8, PROD=16), resolved from ``PATIENT360_ENV``
(the same env resolution the rest of the pipeline uses; default DEV). This
SUPERSEDES the 2026-06-20 note below that "restored" a hardcoded
``max_active_tasks=16``: that change conflated two unrelated reasons.
The shared-stats create race IS resolved (SE audit tables are now per-table
managed UC tables — LLD §2.3 / §13 Decision 12), but LLD §4.1 still mandates
DEV=1 for an INDEPENDENT reason — an 8 GB laptop OOMs running 13 SparkSubmit
tasks in parallel. STAGING/PROD scale up to 8/16 with their infra.

Updated 2026-06-20 (update-dag): [SUPERSEDED — see 2026-06-22 note above]
restore Bronze TaskGroup concurrency to ``max_active_tasks=16``. The
shared-stats create-race reasoning was correct, but hardcoding 16 ignored
the env-dependent OOM constraint in LLD §4.1; 16 is the PROD value only.

Updated 2026-06-20 (update-dag): restore ``catchup=True`` and remove the
stale "disabled while debugging" override. This matches the AC4 unit test
(``test_dag_concurrency_and_max_active_runs`` asserts ``dag.catchup is
True``). Operationally safe because ``max_active_runs=1`` serializes any
backfill — no run flood. NOTE: LLD §4.1 lists catchup as env-dependent
(DEV: False; STAGING/PROD: True); this DAG now uses the STAGING/PROD value.
See report for the LLD-vs-test discrepancy flagged on this run.

This DAG wires the **Bronze TaskGroup + reconciliation_bronze** end of
the pipeline:

* ``bronze_ingestion`` TaskGroup — 13 SparkSubmitOperator tasks (one
  per source table), rendered by
  ``patient_360.bronze.ingestion_factory.build_bronze_taskgroup``.
  Each task invokes ``patient_360.bronze.ingestion_runner`` via the
  ``run_bronze_ingestion.py`` shim under ``airflow/jobs/`` (LLD §4.2).
* ``reconciliation_bronze`` — PythonOperator that runs the
  SE-RUN-EVIDENCE invariant query (LLD §8.6.1): count rows in
  ``unity.bronze.bronze_se_stats`` matching the current
  ``meta_dq_run_id`` / ``ds``. Zero rows ⇒ fail-closed with
  ``SE_RUN_MISSING_FOR_DS=<ds>`` (Spokane 2026-04-26 silent-DQ-skip
  guard; LLD §13 Decision 16).
* ``silver_dimensions`` TaskGroup — 4 hand-wired SparkSubmitOperator
  tasks (``transform_{patients,organizations,providers,payers}_silver``)
  added by STORY-03-007. Each submits ``run_silver_transform.py`` with a
  ``--table`` selector that drives the matching
  ``patient_360.silver.transform_<table>`` SCD2 dimension. Unlike Bronze
  (factory-generated), the silver dims are hand-wired one per module
  (LLD §13 Decision 8 scopes the factory to Bronze). All four fan out in
  parallel downstream of ``reconciliation_bronze`` (LLD §4.3:
  ``RC1 --> SD1 & SD2 & SD3 & SD4``).

The Silver facts, the ``gold_build`` TaskGroup (EPIC-05; 3 Gold consumer
builders via ``run_gold_build.py``), and ``reconciliation_gold`` (STORY-05-006;
SparkSubmitOperator via ``run_gold_recon.py`` ->
``patient_360.gold.reconciliation``) are now wired, with the edge
``gold_build >> reconciliation_gold``. The ``reconciliation_silver`` and
observability (``emit_lineage`` / ``emit_metrics``) tasks from LLD §4.2 are
owned by their own stories and are NOT yet wired here; later stories extend
this DAG.

Dependency edges:
``bronze_ingestion >> reconciliation_bronze`` and
``reconciliation_bronze >> silver_dimensions`` (parallel fan-out).

LLD references: §4.1 (DAG config), §4.2 (task inventory), §4.3 (dependency
diagram), §5.2 (silver dimensions), §5.5 (reconciliation), §8.6.1
(SE-RUN-EVIDENCE).
"""

from __future__ import annotations

import os
from datetime import datetime, timedelta

# ---------------------------------------------------------------------------
# Env-driven paths (LLD §4.1; airflow-dag-pattern.md §3) — NEVER hardcode
# `airflow/configs` or `airflow/jobs` (relative). Paths differ between dev
# workstation, the airflow container, and CI; the env-var indirection is
# the single source of truth. validate-dag rules DAG-PATHS-001 /
# DAG-PATHS-002 enforce this.
# ---------------------------------------------------------------------------
configs_dir = os.environ.get("AIRFLOW_CONFIGS_DIR", "/opt/airflow/configs")
# BRONZE_RUNNER_APP / BRONZE_RECON_APP are wired in
# _infra/docker/docker-compose.yml. They point at the per-task entry
# shims under airflow/jobs/ that the ingestion factory + recon callable
# consume. Listed here for traceability; the factory reads them at
# task-build time.
bronze_runner_app = os.environ.get(
    "BRONZE_RUNNER_APP", "/opt/airflow/jobs/run_bronze_ingestion.py"
)
bronze_recon_app = os.environ.get(
    "BRONZE_RECON_APP", "/opt/airflow/jobs/run_bronze_recon.py"
)
# Silver dimension transforms share a single parameterised entry shim
# (run_silver_transform.py --table <t>); STORY-03-007. Env-indirected for
# the same dev/container/CI path-divergence reason as the bronze apps.
silver_transform_app = os.environ.get(
    "SILVER_TRANSFORM_APP", "/opt/airflow/jobs/run_silver_transform.py"
)
# Gold builders share a single parameterised entry shim
# (run_gold_build.py --table <t>); EPIC-05 (create-gold Phase 5). Env-indirected
# for the same dev/container/CI path-divergence reason as the silver/bronze apps.
gold_build_app = os.environ.get(
    "GOLD_BUILD_APP", "/opt/airflow/jobs/run_gold_build.py"
)
# reconciliation_gold runs its own fixed entry shim (run_gold_recon.py ->
# patient_360.gold.reconciliation.main); EPIC-05 STORY-05-006. Env-indirected
# for the same dev/container/CI path-divergence reason as the build apps.
gold_recon_app = os.environ.get(
    "GOLD_RECON_APP", "/opt/airflow/jobs/run_gold_recon.py"
)


# ---------------------------------------------------------------------------
# Environment-dependent concurrency (LLD §4.1) — NEVER hardcode a single
# value. `max_active_tasks` MUST vary by deployment env: DEV=1, STAGING=8,
# PROD=16. DEV=1 is mandatory because an 8 GB laptop OOMs running 13
# SparkSubmit tasks in parallel (a constraint independent of the
# now-resolved shared-stats race). Resolved from `PATIENT360_ENV` — the
# same env var `reconciliation.py` / `run_silver_transform.py` read, with
# the same DEV default.
# ---------------------------------------------------------------------------
DEPLOY_ENV = os.environ.get("PATIENT360_ENV", "DEV").upper()
MAX_ACTIVE_TASKS_BY_ENV = {"DEV": 1, "STAGING": 8, "PROD": 16}
MAX_ACTIVE_TASKS = MAX_ACTIVE_TASKS_BY_ENV.get(DEPLOY_ENV, 1)


# ---------------------------------------------------------------------------
# DAG default args (LLD §4.1, §8.1)
# ---------------------------------------------------------------------------
DEFAULT_ARGS = {
    "owner": "patient_360",
    "retries": 3,
    "retry_delay": timedelta(seconds=60),
    "depends_on_past": False,
    "email_on_failure": False,
}


# ---------------------------------------------------------------------------
# DAG factory (Airflow 3.2.1 @dag decorator; LLD §4.1)
# ---------------------------------------------------------------------------
# Imports are lazy / module-level here because the Airflow DAG parser
# imports this file on every scheduler heartbeat — keep it cheap.
from airflow.sdk import dag  # type: ignore[import-not-found]  # noqa: E402


@dag(
    dag_id="patient360_hourly_v1",
    description=(
        "Patient 360 hourly medallion pipeline — Bronze + reconciliation "
        "(LLD §4)"
    ),
    schedule="0 * * * *",  # hourly, top of the hour (LLD §4.1)
    start_date=datetime(2026, 1, 1),
    catchup=True,  # AC4 (test_dag_concurrency_and_max_active_runs asserts
    # dag.catchup is True). Backfill is serialized by max_active_runs=1
    # below, so re-enabling cannot produce a run flood. LLD §4.1 marks
    # catchup as env-dependent (DEV: False; STAGING/PROD: True) — this is
    # the STAGING/PROD value. Restored 2026-06-20 (debugging override
    # removed).
    max_active_runs=1,  # prevent overlapping hourly runs + serialize any
    # catchup backfill (LLD §4.1)
    # Env-dependent concurrency per LLD §4.1: DEV=1, STAGING=8, PROD=16
    # (resolved above from PATIENT360_ENV; default DEV). DEV=1 prevents the
    # 8 GB-laptop OOM when 13 Bronze SparkSubmit tasks would otherwise fan
    # out in parallel. The shared-stats cold-warehouse create race is
    # separately resolved (SE audit tables are now per-table managed UC
    # tables — LLD §2.3 / §13 Decision 12), but that does NOT license a
    # hardcoded 16; 16 is the PROD value only.
    max_active_tasks=MAX_ACTIVE_TASKS,
    default_args=DEFAULT_ARGS,
    dagrun_timeout=timedelta(minutes=60),  # default_timeout=60 (LLD §4.1)
    tags=["patient_360", "medallion", "bronze", "silver", "gold"],
    doc_md=__doc__,
)
def patient360_hourly_v1():
    """Build the DAG body. Imports are local so the file remains
    importable in non-Airflow contexts (unit tests via importlib)."""
    from airflow.sdk.definitions._internal.contextmanager import (  # type: ignore[import-not-found]
        DagContext,
    )

    from patient_360.bronze.ingestion_factory import build_bronze_taskgroup

    # The factory needs an explicit DAG reference because Airflow 3.x
    # validates the TaskGroup `dag` attr eagerly (None raises before
    # the DagContext fallback fires). Pull the active DAG out of the
    # context stack the @dag decorator pushes on entry.
    current_dag = DagContext.get_current()

    # Bronze TaskGroup — factory generates one SparkSubmitOperator per
    # per-table YAML in `airflow/configs/` (LLD §4.2). The factory
    # itself is responsible for the 13-task fan-out; this DAG only owns
    # the orchestration glue.
    bronze_tg = build_bronze_taskgroup(current_dag, configs_dir)

    # reconciliation_bronze — SE-RUN-EVIDENCE invariant (LLD §8.6.1).
    # Runs as SparkSubmitOperator (NOT PythonOperator). Airflow 3.x's
    # task SDK + an in-process SparkContext collide on
    # `_start_update_server(is_unix_domain_sock=...)` and raise
    # TypeError at SparkContext._do_init — Spark needs its own JVM.
    from airflow.providers.apache.spark.operators.spark_submit import (  # type: ignore[import-not-found]
        SparkSubmitOperator,
    )

    from patient_360.bronze.spark_submit_wrapper import (
        DEFAULT_PACKAGES,
        build_spark_conf,
    )

    recon = SparkSubmitOperator(
        task_id="reconciliation_bronze",
        application="/opt/airflow/jobs/run_bronze_recon.py",
        conn_id="spark_default",
        conf=build_spark_conf({}),
        packages=",".join(DEFAULT_PACKAGES),
        application_args=["--ds", "{{ ds }}", "--meta-dq-run-id", "{{ ts_nodash }}"],
        driver_memory="1g",
        executor_memory="1g",
        executor_cores=1,
        num_executors=1,
        retries=1,
        retry_delay=timedelta(seconds=60),
        execution_timeout=timedelta(minutes=20),  # LLD §4.2
    )

    bronze_tg >> recon

    # silver_dimensions TaskGroup (STORY-03-007; LLD §4.2, §4.3, §5.2).
    # Four SCD2 dimension transforms, hand-wired one per silver module
    # (Decision 8 keeps the factory Bronze-only). Each is a
    # SparkSubmitOperator — Airflow 3.x embedded PySpark hangs on
    # classloader collisions, so every Spark-touching task forks its own
    # JVM via spark-submit (LLD §4.2 2026-05-12 pivot). All four fan out
    # from reconciliation_bronze in parallel (§4.3: RC1 --> SD1..SD4).
    from airflow.sdk import TaskGroup  # type: ignore[import-not-found]

    # LLD §4.2 silver_dimensions row — same SE/SCD2 task class, identical
    # retries/timeout. Order is the §4.3 SD1..SD4 order. Task IDs (built via
    # the f-string below; listed literally here for traceability/grep):
    #   transform_patients_silver, transform_organizations_silver,
    #   transform_providers_silver, transform_payers_silver
    silver_dimension_tables = ["patients", "organizations", "providers", "payers"]

    dim_tasks: dict[str, SparkSubmitOperator] = {}
    with TaskGroup(group_id="silver_dimensions", dag=current_dag) as silver_dims:
        for table in silver_dimension_tables:
            dim_tasks[table] = SparkSubmitOperator(
                task_id=f"transform_{table}_silver",
                application=silver_transform_app,
                conn_id="spark_default",
                conf=build_spark_conf({}),
                packages=",".join(DEFAULT_PACKAGES),
                application_args=["--table", table, "--ds", "{{ ds }}"],
                driver_memory="2g",  # LLD §4.2 silver-dim sizing
                executor_memory="2g",
                executor_cores=2,
                num_executors=2,
                retries=2,  # LLD §4.2 "2" retries, 120s exp backoff
                retry_delay=timedelta(seconds=120),
                retry_exponential_backoff=True,
                execution_timeout=timedelta(minutes=45),  # LLD §4.2
            )

    # §4.3 edge: reconciliation_bronze --> SD1 & SD2 & SD3 & SD4.
    recon >> silver_dims

    # silver_facts TaskGroup (EPIC-04; LLD §4.2 silver_facts rows, §4.3
    # dependency diagram). Nine cleansed-fact transforms, each a
    # SparkSubmitOperator running the same parameterised shim with a
    # ``--table`` selector that drives ``patient_360.silver.transform_<table>``.
    # Facts insertInto the pre-created ``unity.silver.<table>`` UC table
    # (dynamic partition overwrite — Decision 12/15). Unlike the dims (SCD2
    # MERGE) these are not ds-merged; idempotency is per-ds overwrite.
    #
    # The TaskGroup is visual grouping ONLY — the real per-task dependency
    # edges from LLD §4.2 Task Inventory are wired explicitly below and must
    # NOT be flattened into a fan-out:
    #   * encounters  <- patients, organizations, providers   (FK dims)
    #   * allergies   <- patients
    #   * conditions/medications/observations/immunizations/procedures/
    #     claims/careplans <- encounters
    #   * reconciliation_silver <- every silver task
    # Task IDs (built via the f-string below; listed literally for grep):
    #   transform_encounters_silver, transform_conditions_silver,
    #   transform_medications_silver, transform_observations_silver,
    #   transform_allergies_silver, transform_immunizations_silver,
    #   transform_procedures_silver, transform_claims_silver,
    #   transform_careplans_silver
    silver_fact_tables = [
        "encounters", "conditions", "medications", "observations", "allergies",
        "immunizations", "procedures", "claims", "careplans",
    ]
    fact_tasks: dict[str, SparkSubmitOperator] = {}
    with TaskGroup(group_id="silver_facts", dag=current_dag) as silver_facts:
        for table in silver_fact_tables:
            fact_tasks[table] = SparkSubmitOperator(
                task_id=f"transform_{table}_silver",
                application=silver_transform_app,
                conn_id="spark_default",
                conf=build_spark_conf({}),
                packages=",".join(DEFAULT_PACKAGES),
                application_args=["--table", table, "--ds", "{{ ds }}"],
                driver_memory="2g",  # LLD §4.2 silver-fact sizing
                executor_memory="2g",
                executor_cores=2,
                num_executors=2,
                retries=2,  # LLD §4.2 "2" retries, 120s exp backoff
                retry_delay=timedelta(seconds=120),
                retry_exponential_backoff=True,
                execution_timeout=timedelta(minutes=45),  # LLD §4.2
            )

    # --- explicit per-task edges (LLD §4.2 / §4.3) -------------------------
    # encounters depends on the three FK dims it joins (is_current=TRUE).
    [
        dim_tasks["patients"],
        dim_tasks["organizations"],
        dim_tasks["providers"],
    ] >> fact_tasks["encounters"]
    # allergies depends only on patients.
    dim_tasks["patients"] >> fact_tasks["allergies"]
    # the remaining facts depend on encounters (encounter FK is required).
    for downstream in (
        "conditions", "medications", "observations", "immunizations",
        "procedures", "claims", "careplans",
    ):
        fact_tasks["encounters"] >> fact_tasks[downstream]

    # NOTE: reconciliation_silver (the SQL-only cross-table query_dq node that
    # depends on every silver task) is owned by STORY-04-010 and wired by its
    # own generator run (run_silver_recon.py shim does not exist yet). It is
    # intentionally NOT added here so this DAG stays runnable.

    # gold_build TaskGroup (EPIC-05; LLD §4.2 gold rows, §5.3/§5.4 module map,
    # create-gold Phase 5). Three Gold consumer builders, each a
    # SparkSubmitOperator running the parameterised shim run_gold_build.py with
    # a ``--table`` selector that drives ``patient_360.gold.build_<table>``.
    # Each builder does inline SE BEFORE a full-overwrite
    # ``insertInto unity.gold.<table>`` (Decision 12/15; no SCD2 in Gold).
    #
    # Mirrors the silver_facts group. The LLD §5.4 table->task_id map is NOT a
    # uniform ``build_<table>_gold`` f-string (patient_clinical_history maps to
    # ``build_clinical_history_gold``, dropping the ``patient_`` prefix), so the
    # task ids are wired from an explicit map. Task IDs (listed literally for
    # grep/traceability):
    #   build_patient_summary_gold, build_clinical_history_gold,
    #   build_billing_summary_gold
    gold_build_tasks = {
        "patient_summary": "build_patient_summary_gold",
        "patient_clinical_history": "build_clinical_history_gold",
        "patient_billing_summary": "build_billing_summary_gold",
    }
    gold_tasks: dict[str, SparkSubmitOperator] = {}
    with TaskGroup(group_id="gold_build", dag=current_dag) as gold_build:
        for table, task_id in gold_build_tasks.items():
            gold_tasks[table] = SparkSubmitOperator(
                task_id=task_id,
                application=gold_build_app,
                conn_id="spark_default",
                conf=build_spark_conf({}),
                packages=",".join(DEFAULT_PACKAGES),
                application_args=["--table", table, "--ds", "{{ ds }}"],
                driver_memory="2g",  # heaviest tasks; mirrors silver-fact sizing
                executor_memory="2g",
                executor_cores=2,
                num_executors=2,
                retries=2,  # LLD §4.2 gold rows: 2 retries, 120s exp backoff
                retry_delay=timedelta(seconds=120),
                retry_exponential_backoff=True,
                execution_timeout=timedelta(minutes=30),  # LLD §4.2 gold rows
            )

    # reconciliation_gold — Gold layer-terminal reconciliation gate (LLD §4.2,
    # §5.5; STORY-05-006). Runs as a SparkSubmitOperator (NOT PythonOperator —
    # same Airflow-3.x-embedded-Spark classloader constraint as
    # reconciliation_bronze) via the fixed run_gold_recon.py shim ->
    # patient_360.gold.reconciliation.main. It reconciles unity.gold.* row
    # counts against their unity.silver.* sources within the DQS §4/§5
    # tolerance, asserts patient_summary completeness (= 5,767 current
    # patients; NFR-4 / DQ-FLD-106), and asserts allergy completeness
    # (DQ-FLD-138). Fails closed and blocks consumer access on breach. LLD §4.2
    # gold-recon sizing: 20 min timeout, 1 retry, 60s fixed backoff.
    gold_recon = SparkSubmitOperator(
        task_id="reconciliation_gold",
        application=gold_recon_app,
        conn_id="spark_default",
        conf=build_spark_conf({}),
        packages=",".join(DEFAULT_PACKAGES),
        application_args=["--ds", "{{ ds }}", "--meta-dq-run-id", "{{ ts_nodash }}"],
        driver_memory="1g",
        executor_memory="1g",
        executor_cores=1,
        num_executors=1,
        retries=1,
        retry_delay=timedelta(seconds=60),
        execution_timeout=timedelta(minutes=20),  # LLD §4.2 reconciliation_gold
    )

    # Dependency edges (create-gold Phase 5): the canonical LLD §4.2 gate is
    # ``reconciliation_silver >> gold_build >> reconciliation_gold``.
    # reconciliation_silver is NOT a node in this DAG yet (owned by
    # STORY-04-010; no run_silver_recon.py shim exists), so gold_build is gated
    # on the existing Silver terminal state — ALL silver dimensions AND facts —
    # which is exactly what reconciliation_silver would gate (Gold reads
    # clinical_patients, clinical_encounters + facts, and reference_payers, so
    # every Silver table must be complete first). When reconciliation_silver is
    # wired, re-point the upstream edge to ``reconciliation_silver >> gold_build``.
    # The downstream ``gold_build >> reconciliation_gold`` edge is now wired
    # (STORY-05-006). The emit_lineage / emit_metrics observability tasks
    # (LLD §4.2, downstream of reconciliation_gold) remain owned by their own
    # stories and are NOT wired here.
    [silver_dims, silver_facts] >> gold_build >> gold_recon


# Instantiate the DAG at module import time so the Airflow scheduler
# picks it up.
dag_instance = patient360_hourly_v1()
