"""Spark-submit entry wrapper for the silver dimension transform tasks.

Generated by ``/developer-plugin:update-silver`` for STORY-03-007 from
``outputs/lld/v1/LLD-2026-05-12-patient-360.md`` (§4.2 task inventory,
§5.2 silver dimensions). Do not hand-edit — re-run the silver generator
to regenerate.

Lifecycle (one task per silver dimension, LLD §4.2):
  Airflow -> SparkSubmitOperator(application=this_file,
                application_args=["--table", "<table>", "--ds", ...])
        -> spark-submit run_silver_transform.py --table patients --ds ...
        -> patient_360.silver.transform_<table>.transform(spark, env, ds)

A single parameterised shim covers all four SCD2 dimensions. ``--table``
selects the matching ``patient_360.silver.transform_<table>`` module; the
module's ``transform(spark, env, ds)`` is the contract (it owns the
bronze read, inline SE, and the SCD2 MERGE). The shim only owns the
SparkSession + argument plumbing so the transform stays import-clean for
unit tests (no SparkSession at import time).
"""

from __future__ import annotations

import argparse
import importlib
import logging
import os
import sys

logger = logging.getLogger(__name__)

# LLD §4.2 / §4.3 silver_dimensions — the four SCD2 dimension transforms.
# Each name maps 1:1 to ``patient_360.silver.transform_<name>`` and to the
# DAG task id ``transform_<name>_silver``. Kept here so an unknown --table
# fails fast with a clear allow-list instead of an opaque ImportError.
DIMENSION_TABLES = ("patients", "organizations", "providers", "payers")

# LLD §4.2 / §4.3 silver_facts — the nine cleansed-fact transforms (EPIC-04).
# Same shim contract: ``--table encounters`` selects
# ``patient_360.silver.transform_encounters`` and the DAG task
# ``transform_encounters_silver``. Facts insertInto the pre-created
# ``unity.silver.<table>`` UC table (dynamic partition overwrite; no SCD2 merge).
FACT_TABLES = (
    "encounters", "conditions", "medications", "observations", "allergies",
    "immunizations", "procedures", "claims", "careplans",
)

SILVER_TABLES = DIMENSION_TABLES + FACT_TABLES


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(description="silver transform entry wrapper")
    p.add_argument(
        "--table",
        required=True,
        choices=SILVER_TABLES,
        help="Silver table to transform (selects transform_<table>).",
    )
    p.add_argument(
        "--ds",
        required=True,
        help="Logical date YYYY-MM-DD (SCD2 effective_date).",
    )
    p.add_argument(
        "--env",
        default=os.environ.get("PATIENT360_ENV", "DEV"),
        help="Deployment env (DEV/TEST/PROD); defaults to PATIENT360_ENV or DEV.",
    )
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    module_name = f"patient_360.silver.transform_{args.table}"
    module = importlib.import_module(module_name)
    if not hasattr(module, "transform"):
        raise AttributeError(
            f"{module_name} has no `transform(spark, env, ds)` — regenerate "
            "this wrapper after the silver transform contract changes."
        )

    # SparkSession built here (NOT in the transform module) so the transform
    # stays importable in pure-Python unit tests. Same Delta+metastore wiring
    # as the bronze runner (delta_helpers.build_spark_session).
    from patient_360.utils.delta_helpers import build_spark_session

    spark = build_spark_session(app_name=f"silver_transform_{args.table}")
    try:
        module.transform(spark, args.env, args.ds)
    finally:
        spark.stop()
    return 0


if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s"
    )
    sys.exit(main(sys.argv[1:]))
