"""Spark-submit entry wrapper for Silver transform tasks.

Generated by /developer-plugin:create-silver from LLD §4.2 / §5.2.
One wrapper for every Silver transform; ``--table`` selects the
module under ``patient_360.silver.transform_<table>``.

Lifecycle:
  Airflow -> SparkSubmitOperator(application=this_file)
        -> spark-submit run_silver_transform.py --table patients --env DEV --ds ...
        -> patient_360.silver.transform_<table>.transform(spark, env, ds)
"""

from __future__ import annotations

import argparse
import importlib
import logging
import sys

from patient_360.utils.delta_helpers import build_spark_session

logger = logging.getLogger(__name__)


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(description="silver_transform entry wrapper")
    p.add_argument(
        "--table",
        required=True,
        help=(
            "Logical Silver table name (e.g. 'patients'); selects the "
            "transform module under `patient_360.silver.transform_<table>`."
        ),
    )
    p.add_argument(
        "--env",
        choices=["DEV", "STAGING", "PROD"],
        default="DEV",
        help="Runtime environment flag (LLD §5.4).",
    )
    p.add_argument(
        "--ds",
        required=True,
        help="Logical date YYYY-MM-DD; SCD2 effective_from for this run.",
    )
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    module_name = f"patient_360.silver.transform_{args.table}"
    transform_mod = importlib.import_module(module_name)
    if not hasattr(transform_mod, "transform"):
        raise AttributeError(
            f"{module_name} has no `transform(spark, env, ds)` callable — "
            "regenerate via /developer-plugin:create-silver."
        )
    spark = build_spark_session(app_name=f"silver_{args.table}")
    try:
        transform_mod.transform(spark, env=args.env, ds=args.ds)
    finally:
        spark.stop()
    return 0


if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s"
    )
    sys.exit(main(sys.argv[1:]))
