"""Patient 360 hourly medallion pipeline DAG (LLD §4.1, §4.2).

Generated by ``/developer-plugin:create-dag`` for STORY-02-006 from
``chapter-4/outputs/lld/v1/LLD-2026-05-21-patient-360.md`` (v1.15).
Updated 2026-05-21 by ``/developer-plugin:update-dag``: DEV
``max_active_tasks`` re-capped from 16 → **1** per LLD v1.15 §4.1 and
§13 Decision 12 Constraints (2026-05-21). Embedded Derby Hive metastore
is single-process; the 2026-05-20 v1.14 raise to 16 reproduced
``ERROR XSDB6: Another instance of Derby may have already booted the
database null``. The ``bootstrap_se`` root task closes the SE-table
CREATE race independently; ``max_active_tasks=1`` closes the Derby
concurrent-metastore-access race. Both gates are required together —
neither alone is sufficient.
Hand-edits are overwritten on the next create-dag run.

This DAG wires the **bootstrap_se + Bronze TaskGroup + reconciliation_bronze**
end of the pipeline:

* ``bootstrap_se`` — root SparkSubmitOperator that idempotently creates
  the shared ``bronze.bronze_se_stats`` / ``bronze.bronze_se_errors``
  Delta tables via ``scripts/bootstrap_se_tables.py`` (resolved via the
  ``SE_BOOTSTRAP_APP`` env var, default
  ``/opt/patient_360/scripts/bootstrap_se_tables.py``). Closes the
  cold-start CREATE-race and warm-restart
  ``DELTA_CREATE_TABLE_WITH_NON_EMPTY_LOCATION`` failure modes
  (LLD-DEVIATIONS row 6; LLD v1.14 §4.2).
* ``bronze_ingestion`` TaskGroup — 13 SparkSubmitOperator tasks (one
  per source table), rendered by
  ``patient_360.bronze.ingestion_factory.build_bronze_taskgroup``.
  Each task invokes ``patient_360.bronze.ingestion_runner`` via the
  ``run_bronze_ingestion.py`` shim under ``airflow/jobs/`` (LLD §4.2).
  All Bronze tasks take ``bootstrap_se`` as an upstream dependency.
* ``reconciliation_bronze`` — SparkSubmitOperator that runs the
  SE-RUN-EVIDENCE invariant query (LLD §8.6.1): count rows in
  ``unity.bronze.bronze_se_stats`` matching the current
  ``meta_dq_run_id`` / ``ds``. Zero rows ⇒ fail-closed with
  ``SE_RUN_MISSING_FOR_DS=<ds>`` (Spokane 2026-04-26 silent-DQ-skip
  guard; LLD §13 Decision 16).

Silver and Gold layers are NOT wired here; later stories (STORY-03-*,
STORY-04-*) extend this DAG with their TaskGroups + reconciliation
tasks per LLD §4.3.

LLD references: §4.1 (DAG config), §4.2 (task inventory), §5.5
(reconciliation), §8.6.1 (SE-RUN-EVIDENCE).
"""

from __future__ import annotations

import os
from datetime import datetime, timedelta

# ---------------------------------------------------------------------------
# Env-driven paths (LLD §4.1; airflow-dag-pattern.md §3) — NEVER hardcode
# `airflow/configs` or `airflow/jobs` (relative). Paths differ between dev
# workstation, the airflow container, and CI; the env-var indirection is
# the single source of truth. validate-dag rules DAG-PATHS-001 /
# DAG-PATHS-002 enforce this.
# ---------------------------------------------------------------------------
configs_dir = os.environ.get("AIRFLOW_CONFIGS_DIR", "/opt/airflow/configs")
# BRONZE_RUNNER_APP / BRONZE_RECON_APP are wired in
# _infra/docker/docker-compose.yml. They point at the per-task entry
# shims under airflow/jobs/ that the ingestion factory + recon callable
# consume. Listed here for traceability; the factory reads them at
# task-build time.
bronze_runner_app = os.environ.get(
    "BRONZE_RUNNER_APP", "/opt/airflow/jobs/run_bronze_ingestion.py"
)
bronze_recon_app = os.environ.get(
    "BRONZE_RECON_APP", "/opt/airflow/jobs/run_bronze_recon.py"
)
# SE shared stats/errors table bootstrap (LLD v1.14 §4.2). Idempotent
# CREATE SCHEMA + CREATE TABLE IF NOT EXISTS for `bronze.bronze_se_stats`
# / `bronze.bronze_se_errors`. Resolved via the SE_BOOTSTRAP_APP env var
# so the same DAG runs on dev workstation, in-container, and CI.
se_bootstrap_app = os.environ.get(
    "SE_BOOTSTRAP_APP", "/opt/patient_360/scripts/bootstrap_se_tables.py"
)
# Silver transform wrapper — single entry-point shared by every Silver
# task in the `silver_dimensions` and `silver_facts` TaskGroups
# (LLD §4.2 / §5.2). Each task selects its module via --table.
silver_transform_app = os.environ.get(
    "SILVER_TRANSFORM_APP", "/opt/airflow/jobs/run_silver_transform.py"
)


# ---------------------------------------------------------------------------
# DAG default args (LLD §4.1, §8.1)
# ---------------------------------------------------------------------------
DEFAULT_ARGS = {
    "owner": "patient_360",
    "retries": 3,
    "retry_delay": timedelta(seconds=60),
    "depends_on_past": False,
    "email_on_failure": False,
}


# ---------------------------------------------------------------------------
# DAG factory (Airflow 3.2.1 @dag decorator; LLD §4.1)
# ---------------------------------------------------------------------------
# Imports are lazy / module-level here because the Airflow DAG parser
# imports this file on every scheduler heartbeat — keep it cheap.
from airflow.sdk import dag  # type: ignore[import-not-found]  # noqa: E402


@dag(
    dag_id="patient360_hourly_v1",
    description=(
        "Patient 360 hourly medallion pipeline — Bronze + reconciliation "
        "(LLD §4)"
    ),
    schedule="0 * * * *",  # hourly, top of the hour (LLD §4.1)
    start_date=datetime(2026, 1, 1),
    catchup=False,  # disable backfill while debugging — was producing
    # an avalanche of scheduled runs (Jan→May hourly) each one leaving
    # orphan Delta files behind on failure. Re-enable for production
    # once Bronze writes are stable end-to-end.
    max_active_runs=1,  # prevent overlapping hourly runs (LLD §4.1)
    # LLD v1.15 §4.1 RE-CAPS DEV concurrency to `max_active_tasks=1`
    # per §13 Decision 12 Constraints (2026-05-21). The embedded Derby
    # Hive metastore selected by §13 Decision 12 is a SINGLE-PROCESS
    # database — only one JVM may open it at a time. With
    # `max_active_tasks=16`, parallel `SparkSubmitOperator` tasks fail
    # with `ERROR XSDB6: Another instance of Derby may have already
    # booted the database null` (reproduced 2026-05-21 on the first
    # DAG run). The 2026-05-20 v1.14 raise from 1 → 16 was based on an
    # incomplete read of the bottleneck and is reverted here. The
    # `bootstrap_se` root task (below) still closes the SE-table
    # CREATE race + warm-restart DELTA_CREATE_TABLE_WITH_NON_EMPTY_LOCATION
    # failure mode (LLD-DEVIATIONS row 6), but it does NOT bypass
    # Derby's concurrent-access limit. Both gates are required
    # together. Raising concurrency > 1 in DEV requires migrating the
    # metastore to a multi-client backend (candidate Decision 16).
    # STAGING/PROD scale per their respective metastore backends.
    max_active_tasks=1,
    default_args=DEFAULT_ARGS,
    dagrun_timeout=timedelta(minutes=60),  # default_timeout=60 (LLD §4.1)
    tags=["patient_360", "medallion", "bronze"],
    doc_md=__doc__,
)
def patient360_hourly_v1():
    """Build the DAG body. Imports are local so the file remains
    importable in non-Airflow contexts (unit tests via importlib)."""
    from airflow.sdk.definitions._internal.contextmanager import (  # type: ignore[import-not-found]
        DagContext,
    )

    from patient_360.bronze.ingestion_factory import build_bronze_taskgroup

    # The factory needs an explicit DAG reference because Airflow 3.x
    # validates the TaskGroup `dag` attr eagerly (None raises before
    # the DagContext fallback fires). Pull the active DAG out of the
    # context stack the @dag decorator pushes on entry.
    current_dag = DagContext.get_current()

    # SparkSubmitOperator + shared spark conf builder are needed for
    # both `bootstrap_se` (root) and `reconciliation_bronze`.
    from airflow.providers.apache.spark.operators.spark_submit import (  # type: ignore[import-not-found]
        SparkSubmitOperator,
    )
    from patient_360.bronze.spark_submit_wrapper import (
        DEFAULT_PACKAGES,
        build_spark_conf,
    )

    # bootstrap_se — one-shot root SparkSubmitOperator that idempotently
    # creates the shared SE Delta tables `bronze.bronze_se_stats` and
    # `bronze.bronze_se_errors` (LLD v1.14 §4.2). Upstream of every
    # Bronze task. Closes LLD-DEVIATIONS row 6 (cold-start CREATE-race +
    # warm-restart DELTA_CREATE_TABLE_WITH_NON_EMPTY_LOCATION).
    bootstrap_se = SparkSubmitOperator(
        task_id="bootstrap_se",
        application=se_bootstrap_app,
        conn_id="spark_default",
        conf=build_spark_conf({}),
        packages=",".join(DEFAULT_PACKAGES),
        driver_memory="1g",
        executor_memory="1g",
        executor_cores=1,
        num_executors=1,
        retries=1,
        retry_delay=timedelta(seconds=60),
        execution_timeout=timedelta(minutes=5),
    )

    # Bronze TaskGroup — factory generates one SparkSubmitOperator per
    # per-table YAML in `airflow/configs/` (LLD §4.2). The factory
    # itself is responsible for the 13-task fan-out; this DAG only owns
    # the orchestration glue. Every task in this TaskGroup takes
    # `bootstrap_se` as an upstream dependency (LLD v1.14 §4.2).
    bronze_tg = build_bronze_taskgroup(current_dag, configs_dir)

    # reconciliation_bronze — SE-RUN-EVIDENCE invariant (LLD §8.6.1).
    # Runs as SparkSubmitOperator (NOT PythonOperator). Airflow 3.x's
    # task SDK + an in-process SparkContext collide on
    # `_start_update_server(is_unix_domain_sock=...)` and raise
    # TypeError at SparkContext._do_init — Spark needs its own JVM.

    recon = SparkSubmitOperator(
        task_id="reconciliation_bronze",
        application=bronze_recon_app,
        conn_id="spark_default",
        conf=build_spark_conf({}),
        packages=",".join(DEFAULT_PACKAGES),
        application_args=["--ds", "{{ ds }}", "--meta-dq-run-id", "{{ ts_nodash }}"],
        driver_memory="1g",
        executor_memory="1g",
        executor_cores=1,
        num_executors=1,
        retries=1,
        retry_delay=timedelta(seconds=60),
        execution_timeout=timedelta(minutes=20),  # LLD §4.2
    )

    # -------------------------------------------------------------------
    # Silver — TaskGroups (LLD §4.3, §5.2)
    # -------------------------------------------------------------------
    # `silver_dimensions` carries the 4 SCD2 dimension transforms
    # (clinical_patients, reference_organizations, reference_providers,
    # reference_payers). `silver_facts` carries the 9 cleansed-fact
    # transforms. We add tasks as their stories land — STORY-03-001
    # delivers clinical_patients today. Sibling stories (STORY-03-002..*,
    # STORY-04-*) extend these TaskGroups incrementally.
    #
    # IL-011: every Spark-touching task is a SparkSubmitOperator
    # (separate JVM). PythonOperator + build_spark_session() collides
    # with Airflow 3.x's task SDK on `_start_update_server`.
    from airflow.utils.task_group import TaskGroup  # type: ignore[import-not-found]

    with TaskGroup(
        group_id="silver_dimensions",
        dag=current_dag,
        tooltip="Silver SCD2 dimensions (LLD §5.2)",
    ) as silver_dims:
        SparkSubmitOperator(
            task_id="transform_patients_silver",
            application=silver_transform_app,
            conn_id="spark_default",
            conf=build_spark_conf(
                # IL-012 — driver_cores forwarded via conf, not kwarg.
                {"spark.driver.cores": "1"}
            ),
            packages=",".join(DEFAULT_PACKAGES),
            application_args=[
                "--table", "patients",
                "--env", "{{ var.value.get('patient_360_env', 'DEV') }}",
                "--ds", "{{ ds }}",
            ],
            driver_memory="1g",
            executor_memory="1g",
            executor_cores=1,
            num_executors=1,
            retries=2,
            retry_delay=timedelta(seconds=120),
            execution_timeout=timedelta(minutes=30),
        )

    with TaskGroup(
        group_id="silver_facts",
        dag=current_dag,
        tooltip="Silver cleansed facts (LLD §5.2) -- populated by STORY-04-*",
    ):
        # STORY-04-* stories add their tasks here.
        pass

    # bootstrap_se runs first, then the Bronze fan-out, then
    # reconciliation, then Silver dimensions. Per LLD v1.14 §4.2, every
    # task in `bronze_ingestion` takes `bootstrap_se` as its upstream.
    bootstrap_se >> bronze_tg >> recon >> [silver_dims]


# Instantiate the DAG at module import time so the Airflow scheduler
# picks it up.
dag_instance = patient360_hourly_v1()
