"""Patient 360 hourly medallion pipeline DAG (LLD §4.1, §4.2).

Generated by ``/developer-plugin:create-dag`` for STORY-02-006 from
``chapter-4/outputs/lld/v1/LLD-2026-05-11-patient-360.md``. Hand-edits
are overwritten on the next create-dag run.

This DAG wires the **Bronze TaskGroup + reconciliation_bronze** end of
the pipeline:

* ``bronze_ingestion`` TaskGroup — 13 SparkSubmitOperator tasks (one
  per source table), rendered by
  ``patient_360.bronze.ingestion_factory.build_bronze_taskgroup``.
  Each task invokes ``patient_360.bronze.ingestion_runner`` via the
  ``run_bronze_ingestion.py`` shim under ``airflow/jobs/`` (LLD §4.2).
* ``reconciliation_bronze`` — PythonOperator that runs the
  SE-RUN-EVIDENCE invariant query (LLD §8.6.1): count rows in
  ``unity.bronze.bronze_se_stats`` matching the current
  ``meta_dq_run_id`` / ``ds``. Zero rows ⇒ fail-closed with
  ``SE_RUN_MISSING_FOR_DS=<ds>`` (Spokane 2026-04-26 silent-DQ-skip
  guard; LLD §13 Decision 16).

Silver and Gold layers are NOT wired here; later stories (STORY-03-*,
STORY-04-*) extend this DAG with their TaskGroups + reconciliation
tasks per LLD §4.3.

LLD references: §4.1 (DAG config), §4.2 (task inventory), §5.5
(reconciliation), §8.6.1 (SE-RUN-EVIDENCE).
"""

from __future__ import annotations

import os
from datetime import datetime, timedelta

# ---------------------------------------------------------------------------
# Env-driven paths (LLD §4.1; airflow-dag-pattern.md §3) — NEVER hardcode
# `airflow/configs` or `airflow/jobs` (relative). Paths differ between dev
# workstation, the airflow container, and CI; the env-var indirection is
# the single source of truth. validate-dag rules DAG-PATHS-001 /
# DAG-PATHS-002 enforce this.
# ---------------------------------------------------------------------------
configs_dir = os.environ.get("AIRFLOW_CONFIGS_DIR", "/opt/airflow/configs")
# BRONZE_RUNNER_APP / BRONZE_RECON_APP are wired in
# _infra/docker/docker-compose.yml. They point at the per-task entry
# shims under airflow/jobs/ that the ingestion factory + recon callable
# consume. Listed here for traceability; the factory reads them at
# task-build time.
bronze_runner_app = os.environ.get(
    "BRONZE_RUNNER_APP", "/opt/airflow/jobs/run_bronze_ingestion.py"
)
bronze_recon_app = os.environ.get(
    "BRONZE_RECON_APP", "/opt/airflow/jobs/run_bronze_recon.py"
)


# ---------------------------------------------------------------------------
# DAG default args (LLD §4.1, §8.1)
# ---------------------------------------------------------------------------
DEFAULT_ARGS = {
    "owner": "patient_360",
    "retries": 3,
    "retry_delay": timedelta(seconds=60),
    "depends_on_past": False,
    "email_on_failure": False,
}


# ---------------------------------------------------------------------------
# DAG factory (Airflow 3.2.1 @dag decorator; LLD §4.1)
# ---------------------------------------------------------------------------
# Imports are lazy / module-level here because the Airflow DAG parser
# imports this file on every scheduler heartbeat — keep it cheap.
from airflow.sdk import dag  # type: ignore[import-not-found]  # noqa: E402


@dag(
    dag_id="patient360_hourly_v1",
    description=(
        "Patient 360 hourly medallion pipeline — Bronze + reconciliation "
        "(LLD §4)"
    ),
    schedule="0 * * * *",  # hourly, top of the hour (LLD §4.1)
    start_date=datetime(2026, 1, 1),
    catchup=False,  # disable backfill while debugging — was producing
    # an avalanche of scheduled runs (Jan→May hourly) each one leaving
    # orphan Delta files behind on failure. Re-enable for production
    # once Bronze writes are stable end-to-end.
    max_active_runs=1,  # prevent overlapping hourly runs (LLD §4.1)
    # Bronze tasks all write per-run stats to the same shared
    # `bronze_se_stats` Delta table. On a cold warehouse the first task
    # CREATES the table; parallel siblings race and fail with
    # `DELTA_CREATE_TABLE_WITH_NON_EMPTY_LOCATION`. Serialising the
    # Bronze TaskGroup (max_active_tasks=1) lets the first task land
    # the table, then subsequent tasks pure-append. LLD §4.1 originally
    # asked for concurrency=16 — re-raise after we add a one-shot SE
    # bootstrap step or move stats to per-task tables.
    max_active_tasks=1,
    default_args=DEFAULT_ARGS,
    dagrun_timeout=timedelta(minutes=60),  # default_timeout=60 (LLD §4.1)
    tags=["patient_360", "medallion", "bronze"],
    doc_md=__doc__,
)
def patient360_hourly_v1():
    """Build the DAG body. Imports are local so the file remains
    importable in non-Airflow contexts (unit tests via importlib)."""
    from airflow.sdk.definitions._internal.contextmanager import (  # type: ignore[import-not-found]
        DagContext,
    )

    from patient_360.bronze.ingestion_factory import build_bronze_taskgroup
    from patient_360.bronze.spark_submit_wrapper import build_spark_submit_task

    # The factory needs an explicit DAG reference because Airflow 3.x
    # validates the TaskGroup `dag` attr eagerly (None raises before
    # the DagContext fallback fires). Pull the active DAG out of the
    # context stack the @dag decorator pushes on entry.
    current_dag = DagContext.get_current()

    # Bronze TaskGroup — factory generates one SparkSubmitOperator per
    # per-table YAML in `airflow/configs/` (LLD §4.2). The factory
    # itself is responsible for the 13-task fan-out; this DAG only owns
    # the orchestration glue.
    bronze_tg = build_bronze_taskgroup(current_dag, configs_dir)

    # reconciliation_bronze — SE-RUN-EVIDENCE invariant (LLD §8.6.1).
    # Runs as SparkSubmitOperator (NOT PythonOperator). Airflow 3.x's
    # task SDK + an in-process SparkContext collide on
    # `_start_update_server(is_unix_domain_sock=...)` and raise
    # TypeError at SparkContext._do_init — Spark needs its own JVM.
    from airflow.providers.apache.spark.operators.spark_submit import (  # type: ignore[import-not-found]
        SparkSubmitOperator,
    )
    from patient_360.bronze.spark_submit_wrapper import (
        DEFAULT_PACKAGES,
        build_spark_conf,
    )

    recon = SparkSubmitOperator(
        task_id="reconciliation_bronze",
        application="/opt/airflow/jobs/run_bronze_recon.py",
        conn_id="spark_default",
        conf=build_spark_conf({}),
        packages=",".join(DEFAULT_PACKAGES),
        application_args=["--ds", "{{ ds }}", "--meta-dq-run-id", "{{ ts_nodash }}"],
        driver_memory="1g",
        executor_memory="1g",
        executor_cores=1,
        num_executors=1,
        retries=1,
        retry_delay=timedelta(seconds=60),
        execution_timeout=timedelta(minutes=20),  # LLD §4.2
    )

    bronze_tg >> recon


# Instantiate the DAG at module import time so the Airflow scheduler
# picks it up.
dag_instance = patient360_hourly_v1()
