"""Configuration loading utilities for Planning with Intent.

This module provides functions for loading and parsing the pwi.yaml
configuration file.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

from pwi.config.schema import PWIConfig


class ConfigurationError(Exception):
    """Raised when there's an error loading or parsing configuration."""


def find_config_file(start_path: Path | None = None) -> Path | None:
    """Find the pwi.yaml configuration file.

    Searches in the following order:
    1. Current directory
    2. Parent directories (up to root)
    3. .pwi directory in home

    Args:
        start_path: Starting directory for search. Defaults to current directory.

    Returns:
        Path to config file if found, None otherwise.
    """
    if start_path is None:
        start_path = Path.cwd()

    # Check current and parent directories
    current = start_path
    while current != current.parent:
        config_path = current / "pwi.yaml"
        if config_path.exists():
            return config_path
        current = current.parent

    # Check home directory .pwi folder
    home_config = Path.home() / ".pwi" / "pwi.yaml"
    if home_config.exists():
        return home_config

    return None


def load_yaml(path: Path) -> dict[str, Any]:
    """Load a YAML file and return its contents.

    Args:
        path: Path to the YAML file.

    Returns:
        Parsed YAML contents as a dictionary.

    Raises:
        ConfigurationError: If the file cannot be read or parsed.
    """
    try:
        with open(path, encoding="utf-8") as f:
            content = yaml.safe_load(f)
            return content if content else {}
    except FileNotFoundError as e:
        raise ConfigurationError(f"Configuration file not found: {path}") from e
    except yaml.YAMLError as e:
        raise ConfigurationError(f"Invalid YAML in configuration file: {e}") from e


def load_config(
    config_path: Path | str | None = None,
    auto_discover: bool = True,
) -> PWIConfig:
    """Load and validate the PWI configuration.

    Args:
        config_path: Explicit path to config file. If None and auto_discover
                     is True, will search for config file.
        auto_discover: Whether to search for config file if not provided.

    Returns:
        Validated PWIConfig object.

    Raises:
        ConfigurationError: If configuration cannot be loaded or is invalid.
    """
    path: Path
    if config_path is not None:
        path = Path(config_path)
        if not path.exists():
            raise ConfigurationError(f"Configuration file not found: {path}")
    elif auto_discover:
        found_path = find_config_file()
        if found_path is None:
            # Return default configuration if no file found
            return PWIConfig()
        path = found_path
    else:
        return PWIConfig()

    # Load and parse YAML
    raw_config = load_yaml(path)

    # Validate with Pydantic
    try:
        config = PWIConfig.model_validate(raw_config)
    except Exception as e:
        raise ConfigurationError(f"Invalid configuration: {e}") from e

    return config


def create_default_config(output_path: Path) -> None:
    """Create a default configuration file.

    Args:
        output_path: Path where the config file should be created.

    Raises:
        ConfigurationError: If the file cannot be written.
    """
    default_config = """# PWI Configuration
# Generated by: pwi init
# Works with any OpenAI API-compatible provider (OpenAI, OpenRouter, Azure, Ollama, etc.)

version: "1.0"

project:
  name: "my-data-project"
  type: "data_engineering"
  output_dir: "./output"
  session_dir: "./.pwi/sessions"

llm:
  # OpenAI API compatible settings - resolved from environment variables
  # Required environment variables:
  #   LLM_API_KEY   - Your API key
  #   LLM_BASE_URL  - API endpoint (e.g., https://api.openai.com/v1)
  #   LLM_MODEL     - Model name (e.g., gpt-4o-mini, claude-3-5-sonnet)
  base_url: "${LLM_BASE_URL}"
  api_key: "${LLM_API_KEY}"
  default_model: "${LLM_MODEL}"
  enable_usage_tracking: true

  # Model aliases for agent configuration
  models:
    fast: "${LLM_MODEL}"
    balanced: "${LLM_MODEL}"
    powerful: "${LLM_MODEL}"

agents:
  data_analyst:
    model: "balanced"
    temperature: 0.7
  data_architect:
    model: "powerful"
    temperature: 0.5
  mapping_engineer:
    model: "balanced"
    temperature: 0.3
  dq_engineer:
    model: "balanced"
    temperature: 0.3
  story_writer:
    model: "balanced"
    temperature: 0.8
  sync_agent:
    model: "fast"
    temperature: 0.2

review:
  default_mode: "cli"
  timeout_minutes: 60

logging:
  level: "INFO"
  format: "json"
"""
    try:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(default_config)
    except OSError as e:
        raise ConfigurationError(f"Failed to write configuration file: {e}") from e
