#!/usr/bin/env python3
"""Generate environment-specific config-template.yaml from LLD Section 7.

Reads an LLD markdown file, extracts the Configuration Schema section (§7),
parses parameter tables, and generates a structured YAML config template
with DEV/STAGING/PROD environment sections.

Usage:
    python generate_config_template.py <path-to-lld.md> -o <output-dir>

Exit Codes:
    0: Config template generated successfully
    1: Section 7 not found or no parameters extracted
    2: File not found or parse error
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path


def _extract_section_7(content: str) -> str | None:
    """Extract the Configuration Schema section from LLD content."""
    sections: dict[str, str] = {}
    current_heading = ""
    current_lines: list[str] = []

    for line in content.split("\n"):
        if line.startswith("## "):
            if current_heading:
                sections[current_heading] = "\n".join(current_lines).strip()
            current_heading = line.lstrip("# ").strip()
            current_lines = []
        else:
            current_lines.append(line)

    if current_heading:
        sections[current_heading] = "\n".join(current_lines).strip()

    return sections.get("7. Configuration Schema")


def _parse_parameter_table(section_content: str) -> list[dict[str, str]]:
    """Parse markdown tables in the section to extract parameters.

    Returns a list of dicts with keys: parameter, type, default, description.
    """
    params: list[dict[str, str]] = []
    lines = section_content.strip().split("\n")

    in_table = False
    headers: list[str] = []

    for line in lines:
        stripped = line.strip()
        if not stripped.startswith("|"):
            in_table = False
            headers = []
            continue

        # Skip separator rows
        if all(c in "|- " for c in stripped):
            in_table = True
            continue

        cells = [c.strip() for c in stripped.split("|")[1:-1]]

        if not in_table:
            # This is a header row
            headers = [h.lower().strip("* ") for h in cells]
            continue

        if headers and len(cells) >= len(headers):
            row = dict(zip(headers, cells))
            if any(v for v in row.values()):
                params.append(row)

    return params


def _categorize_parameter(param_name: str) -> str:
    """Guess a category for a parameter based on its name."""
    name_lower = param_name.lower()
    if any(kw in name_lower for kw in ["schedule", "cron", "interval", "frequency"]):
        return "scheduling"
    if any(kw in name_lower for kw in ["memory", "core", "executor", "driver", "partition"]):
        return "compute"
    if any(kw in name_lower for kw in ["path", "format", "compress", "storage", "warehouse"]):
        return "storage"
    if any(kw in name_lower for kw in ["retry", "timeout", "dead_letter", "backoff"]):
        return "error_handling"
    if any(kw in name_lower for kw in ["alert", "metric", "monitor", "log", "dashboard"]):
        return "monitoring"
    return "general"


def generate_config_yaml(params: list[dict[str, str]], pipeline_name: str = "patient-360") -> str:
    """Generate a YAML config template string from extracted parameters."""
    # Group params by category
    categories: dict[str, list[dict[str, str]]] = {}
    for param in params:
        param_name = param.get("parameter", param.get("name", "unknown"))
        category = _categorize_parameter(param_name)
        categories.setdefault(category, []).append(param)

    lines = [
        f"# Configuration Template: {pipeline_name}",
        "# Auto-generated from LLD Section 7 — Configuration Schema",
        "# Generated by: generate_config_template.py",
        "",
        "pipeline:",
        f"  name: {pipeline_name}",
        '  version: "1.0"',
        "",
        "environments:",
    ]

    for env in ["DEV", "STAGING", "PROD"]:
        lines.append(f"  {env}:")
        for category, cat_params in sorted(categories.items()):
            lines.append(f"    {category}:")
            for param in cat_params:
                param_name = param.get("parameter", param.get("name", "unknown"))
                default_val = param.get("default", param.get("value", '""'))
                description = param.get("description", "")
                # Clean up param name for YAML key
                yaml_key = re.sub(r"[^a-z0-9_]", "_", param_name.lower().strip())
                yaml_key = re.sub(r"_+", "_", yaml_key).strip("_")
                if description:
                    lines.append(f"      # {description}")
                lines.append(f"      {yaml_key}: {default_val}")
            lines.append("")
        lines.append("")

    return "\n".join(lines)


def main() -> int:
    """CLI entry point."""
    parser = argparse.ArgumentParser(
        description="Generate config-template.yaml from LLD Section 7",
    )
    parser.add_argument(
        "path",
        type=Path,
        help="Path to LLD markdown file",
    )
    parser.add_argument(
        "-o",
        "--output-dir",
        type=Path,
        default=None,
        help="Output directory for config-template.yaml (default: same dir as LLD + /config/)",
    )

    args = parser.parse_args()

    if not args.path.is_file():
        print(f"Error: {args.path} is not a file.", file=sys.stderr)
        return 2

    try:
        content = args.path.read_text(encoding="utf-8")
    except Exception as e:
        print(f"Error reading file: {e}", file=sys.stderr)
        return 2

    section_7 = _extract_section_7(content)
    if not section_7:
        print("Error: Section '7. Configuration Schema' not found in LLD.", file=sys.stderr)
        return 1

    params = _parse_parameter_table(section_7)
    if not params:
        print(
            "Warning: No parameters extracted from Section 7 tables."
            " Generating template with placeholder structure.",
            file=sys.stderr,
        )
        # Generate a minimal template even without parsed params
        params = [
            {
                "parameter": "placeholder",
                "default": '""',
                "description": "Add parameters to LLD Section 7",
            },
        ]

    # Extract pipeline name from LLD title if possible
    title_match = re.search(r"^#\s+.*:\s*(.+)", content, re.MULTILINE)
    pipeline_name = (
        title_match.group(1).strip().lower().replace(" ", "-") if title_match else "pipeline"
    )

    yaml_content = generate_config_yaml(params, pipeline_name)

    output_dir = args.output_dir or (args.path.parent / "config")
    os.makedirs(output_dir, exist_ok=True)
    output_path = output_dir / "config-template.yaml"

    output_path.write_text(yaml_content, encoding="utf-8")
    print(f"Config template written to: {output_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
