"""Markdown validation and formatting utilities.

This module provides tools for validating and formatting markdown content
generated by agents, ensuring proper structure and syntax.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from enum import Enum
from typing import Any

from markdown_it import MarkdownIt
from mdit_py_plugins.front_matter import front_matter_plugin

from pwi.utils.logging import get_logger

logger = get_logger("utils.markdown")


class IssueSeverity(Enum):
    """Severity levels for validation issues."""

    ERROR = "error"
    WARNING = "warning"
    INFO = "info"


class IssueCategory(Enum):
    """Categories of validation issues."""

    STRUCTURE = "structure"
    SYNTAX = "syntax"
    FORMATTING = "formatting"
    MERMAID = "mermaid"
    TABLE = "table"
    CODE_BLOCK = "code_block"
    HEADING = "heading"
    LIST = "list"


@dataclass
class ValidationIssue:
    """Represents a single validation issue found in markdown content."""

    message: str
    severity: IssueSeverity
    category: IssueCategory
    line: int | None = None
    column: int | None = None
    suggestion: str | None = None

    def __str__(self) -> str:
        loc = f"line {self.line}" if self.line else "unknown location"
        return f"[{self.severity.value.upper()}] {self.category.value}: {self.message} ({loc})"


@dataclass
class ValidationResult:
    """Result of markdown validation."""

    is_valid: bool
    issues: list[ValidationIssue] = field(default_factory=list)
    formatted_content: str | None = None
    metadata: dict[str, Any] = field(default_factory=dict)

    @property
    def error_count(self) -> int:
        """Count of error-level issues."""
        return sum(1 for issue in self.issues if issue.severity == IssueSeverity.ERROR)

    @property
    def warning_count(self) -> int:
        """Count of warning-level issues."""
        return sum(1 for issue in self.issues if issue.severity == IssueSeverity.WARNING)

    def get_issues_by_category(self, category: IssueCategory) -> list[ValidationIssue]:
        """Get all issues of a specific category."""
        return [issue for issue in self.issues if issue.category == category]


class MarkdownValidator:
    """Validates and formats markdown content.

    This validator checks for common issues in agent-generated markdown:
    - Unclosed code blocks
    - Malformed tables
    - Invalid Mermaid diagram syntax
    - Improper heading hierarchy
    - Line length issues
    - Unclosed list items
    """

    # Maximum recommended line length for markdown
    MAX_LINE_LENGTH = 120

    # Valid Mermaid diagram types
    MERMAID_TYPES = {
        "graph",
        "flowchart",
        "sequenceDiagram",
        "classDiagram",
        "stateDiagram",
        "stateDiagram-v2",
        "erDiagram",
        "journey",
        "gantt",
        "pie",
        "quadrantChart",
        "requirementDiagram",
        "gitGraph",
        "mindmap",
        "timeline",
        "sankey-beta",
        "xychart-beta",
        "block-beta",
    }

    def __init__(
        self,
        max_line_length: int = MAX_LINE_LENGTH,
        strict_mermaid: bool = True,
        fix_formatting: bool = True,
    ) -> None:
        """Initialize the validator.

        Args:
            max_line_length: Maximum allowed line length.
            strict_mermaid: Whether to validate Mermaid syntax strictly.
            fix_formatting: Whether to attempt to fix formatting issues.
        """
        self.max_line_length = max_line_length
        self.strict_mermaid = strict_mermaid
        self.fix_formatting = fix_formatting

        # Initialize markdown-it parser
        # Use "commonmark" to avoid optional linkify dependency
        self.md = MarkdownIt("commonmark")
        # Enable tables extension for GFM-like table parsing
        self.md.enable("table")
        front_matter_plugin(self.md)

    def validate(self, content: str) -> ValidationResult:
        """Validate markdown content.

        Args:
            content: The markdown content to validate.

        Returns:
            ValidationResult with issues found and optionally formatted content.
        """
        issues: list[ValidationIssue] = []

        # Run all validation checks
        issues.extend(self._check_code_blocks(content))
        issues.extend(self._check_mermaid_diagrams(content))
        issues.extend(self._check_tables(content))
        issues.extend(self._check_headings(content))
        issues.extend(self._check_line_length(content))
        issues.extend(self._check_lists(content))

        # Try to parse with markdown-it for structural validation
        try:
            tokens = self.md.parse(content)
            issues.extend(self._validate_tokens(tokens))
        except Exception as e:
            issues.append(
                ValidationIssue(
                    message=f"Failed to parse markdown: {e}",
                    severity=IssueSeverity.ERROR,
                    category=IssueCategory.SYNTAX,
                )
            )

        # Attempt to fix formatting if enabled
        formatted_content = None
        if self.fix_formatting:
            formatted_content = self._fix_formatting(content, issues)

        # Determine validity
        has_errors = any(issue.severity == IssueSeverity.ERROR for issue in issues)

        return ValidationResult(
            is_valid=not has_errors,
            issues=issues,
            formatted_content=formatted_content,
            metadata={
                "line_count": len(content.splitlines()),
                "char_count": len(content),
            },
        )

    def _check_code_blocks(self, content: str) -> list[ValidationIssue]:
        """Check for unclosed or malformed code blocks."""
        issues: list[ValidationIssue] = []
        lines = content.splitlines()

        in_code_block = False
        code_block_start_line = 0
        code_block_lang = ""

        for i, line in enumerate(lines, 1):
            stripped = line.strip()

            if stripped.startswith("```"):
                if not in_code_block:
                    in_code_block = True
                    code_block_start_line = i
                    code_block_lang = stripped[3:].strip()
                else:
                    in_code_block = False
                    code_block_start_line = 0

        if in_code_block:
            issues.append(
                ValidationIssue(
                    message=f"Unclosed code block starting at line {code_block_start_line}",
                    severity=IssueSeverity.ERROR,
                    category=IssueCategory.CODE_BLOCK,
                    line=code_block_start_line,
                    suggestion=f"Add closing ``` after the {code_block_lang or 'code'} block",
                )
            )

        return issues

    def _check_mermaid_diagrams(self, content: str) -> list[ValidationIssue]:
        """Check Mermaid diagram syntax."""
        issues: list[ValidationIssue] = []

        # Find all mermaid code blocks
        mermaid_pattern = re.compile(
            r"```mermaid\s*\n(.*?)```",
            re.DOTALL | re.IGNORECASE,
        )

        for match in mermaid_pattern.finditer(content):
            diagram_content = match.group(1).strip()
            start_pos = match.start()
            line_num = content[:start_pos].count("\n") + 1

            # Check if diagram type is valid
            first_line = diagram_content.split("\n")[0].strip() if diagram_content else ""
            diagram_type = first_line.split()[0] if first_line else ""

            # Handle direction specifier (e.g., "graph TD" -> "graph")
            if not diagram_type:
                issues.append(
                    ValidationIssue(
                        message="Empty Mermaid diagram",
                        severity=IssueSeverity.ERROR,
                        category=IssueCategory.MERMAID,
                        line=line_num,
                        suggestion="Add diagram content (e.g., 'flowchart TD')",
                    )
                )
            elif diagram_type not in self.MERMAID_TYPES:
                issues.append(
                    ValidationIssue(
                        message=f"Unknown Mermaid diagram type: '{diagram_type}'",
                        severity=IssueSeverity.WARNING,
                        category=IssueCategory.MERMAID,
                        line=line_num,
                        suggestion=f"Valid types: {', '.join(sorted(self.MERMAID_TYPES)[:5])}...",
                    )
                )

            # Check for common Mermaid syntax issues
            if self.strict_mermaid:
                issues.extend(self._validate_mermaid_syntax(diagram_content, line_num))

        return issues

    def _validate_mermaid_syntax(
        self, diagram_content: str, start_line: int
    ) -> list[ValidationIssue]:
        """Validate Mermaid diagram syntax in detail."""
        issues: list[ValidationIssue] = []
        lines = diagram_content.splitlines()

        # Check for unclosed brackets
        bracket_pairs = {"(": ")", "[": "]", "{": "}", "<": ">"}
        for i, line in enumerate(lines, start_line):
            stack: list[str] = []
            for char in line:
                if char in bracket_pairs:
                    stack.append(char)
                elif char in bracket_pairs.values():
                    if not stack:
                        issues.append(
                            ValidationIssue(
                                message=f"Unmatched closing bracket '{char}'",
                                severity=IssueSeverity.WARNING,
                                category=IssueCategory.MERMAID,
                                line=i,
                            )
                        )
                    else:
                        opener = stack.pop()
                        if bracket_pairs[opener] != char:
                            issues.append(
                                ValidationIssue(
                                    message=f"Mismatched brackets: '{opener}' and '{char}'",
                                    severity=IssueSeverity.WARNING,
                                    category=IssueCategory.MERMAID,
                                    line=i,
                                )
                            )
            if stack:
                issues.append(
                    ValidationIssue(
                        message=f"Unclosed brackets: {stack}",
                        severity=IssueSeverity.WARNING,
                        category=IssueCategory.MERMAID,
                        line=i,
                    )
                )

        # Check for unquoted labels with special characters
        label_pattern = re.compile(r'\[([^\]"]+)\]')
        for i, line in enumerate(lines, start_line):
            for match in label_pattern.finditer(line):
                label = match.group(1)
                if any(c in label for c in "&<>"):
                    issues.append(
                        ValidationIssue(
                            message=f"Label may need quoting: '{label}'",
                            severity=IssueSeverity.INFO,
                            category=IssueCategory.MERMAID,
                            line=i,
                            suggestion='Wrap label in quotes: ["label"]',
                        )
                    )

        return issues

    def _check_tables(self, content: str) -> list[ValidationIssue]:
        """Check for malformed markdown tables."""
        issues: list[ValidationIssue] = []
        lines = content.splitlines()

        table_start = None
        header_cols = 0

        for i, line in enumerate(lines, 1):
            stripped = line.strip()

            # Detect table header row
            if "|" in stripped and table_start is None:
                # Count columns
                cols = len([c for c in stripped.split("|") if c.strip()])
                # Check if next line is separator
                if i < len(lines):
                    next_line = lines[i].strip() if i < len(lines) else ""
                    if re.match(r"^\|?\s*[-:]+[-|\s:]+\|?\s*$", next_line):
                        table_start = i
                        header_cols = cols

            # Check table rows
            elif table_start is not None and "|" in stripped:
                row_cols = len([c for c in stripped.split("|") if c.strip()])
                if row_cols != header_cols:
                    issues.append(
                        ValidationIssue(
                            message=(
                                f"Table row has {row_cols} columns, "
                                f"expected {header_cols} (header at line {table_start})"
                            ),
                            severity=IssueSeverity.WARNING,
                            category=IssueCategory.TABLE,
                            line=i,
                        )
                    )

            # End of table
            elif table_start is not None and not stripped.startswith("|"):
                if stripped:  # Non-empty line ends table
                    table_start = None
                    header_cols = 0

        return issues

    def _check_headings(self, content: str) -> list[ValidationIssue]:
        """Check heading hierarchy."""
        issues: list[ValidationIssue] = []
        lines = content.splitlines()

        prev_level = 0
        in_code_block = False

        for i, line in enumerate(lines, 1):
            # Track code blocks to skip headings inside them
            if line.strip().startswith("```"):
                in_code_block = not in_code_block
                continue

            if in_code_block:
                continue

            # Check for heading
            match = re.match(r"^(#{1,6})\s+(.+)$", line)
            if match:
                level = len(match.group(1))

                # Check for skipped levels
                if prev_level > 0 and level > prev_level + 1:
                    issues.append(
                        ValidationIssue(
                            message=(
                                f"Heading level jumped from {prev_level} to {level} "
                                f"(skipped level {prev_level + 1})"
                            ),
                            severity=IssueSeverity.INFO,
                            category=IssueCategory.HEADING,
                            line=i,
                        )
                    )

                prev_level = level

        return issues

    def _check_line_length(self, content: str) -> list[ValidationIssue]:
        """Check for overly long lines."""
        issues: list[ValidationIssue] = []
        lines = content.splitlines()

        in_code_block = False
        in_table = False

        for i, line in enumerate(lines, 1):
            stripped = line.strip()

            # Track code blocks and tables (where long lines may be acceptable)
            if stripped.startswith("```"):
                in_code_block = not in_code_block
            if stripped.startswith("|"):
                in_table = True
            elif stripped and not stripped.startswith("|"):
                in_table = False

            # Skip code blocks and tables for line length checks
            if in_code_block or in_table:
                continue

            if len(line) > self.max_line_length:
                issues.append(
                    ValidationIssue(
                        message=f"Line exceeds {self.max_line_length} characters ({len(line)} chars)",
                        severity=IssueSeverity.INFO,
                        category=IssueCategory.FORMATTING,
                        line=i,
                        suggestion="Consider breaking into multiple lines",
                    )
                )

        return issues

    def _check_lists(self, content: str) -> list[ValidationIssue]:
        """Check list formatting."""
        issues: list[ValidationIssue] = []
        lines = content.splitlines()

        in_code_block = False
        prev_indent = 0
        prev_was_list = False

        for i, line in enumerate(lines, 1):
            if line.strip().startswith("```"):
                in_code_block = not in_code_block
                continue

            if in_code_block:
                continue

            # Check for list items
            list_match = re.match(r"^(\s*)([-*+]|\d+\.)\s+(.*)$", line)
            if list_match:
                indent = len(list_match.group(1))

                # Check for inconsistent indentation
                if prev_was_list and indent > prev_indent + 4:
                    issues.append(
                        ValidationIssue(
                            message=(
                                f"Large indentation jump in list "
                                f"({prev_indent} to {indent} spaces)"
                            ),
                            severity=IssueSeverity.INFO,
                            category=IssueCategory.LIST,
                            line=i,
                        )
                    )

                prev_indent = indent
                prev_was_list = True
            else:
                prev_was_list = False

        return issues

    def _validate_tokens(self, tokens: list[Any]) -> list[ValidationIssue]:
        """Validate parsed markdown tokens for structural issues."""
        issues: list[ValidationIssue] = []

        # Check for deeply nested structures
        def check_nesting(toks: list[Any], depth: int = 0) -> None:
            if depth > 10:
                issues.append(
                    ValidationIssue(
                        message=f"Deeply nested structure (depth {depth})",
                        severity=IssueSeverity.WARNING,
                        category=IssueCategory.STRUCTURE,
                    )
                )
                return

            for token in toks:
                if hasattr(token, "children") and token.children:
                    check_nesting(token.children, depth + 1)

        check_nesting(tokens)
        return issues

    def _fix_formatting(
        self, content: str, issues: list[ValidationIssue]
    ) -> str:
        """Attempt to fix common formatting issues.

        Args:
            content: Original markdown content.
            issues: List of detected issues.

        Returns:
            Fixed markdown content.
        """
        fixed = content

        # Fix unclosed code blocks
        code_block_issues = [
            i for i in issues
            if i.category == IssueCategory.CODE_BLOCK and "Unclosed" in i.message
        ]
        if code_block_issues:
            if not fixed.rstrip().endswith("```"):
                fixed = fixed.rstrip() + "\n```\n"

        # Ensure file ends with newline
        if not fixed.endswith("\n"):
            fixed += "\n"

        return fixed


def validate_markdown(content: str, **kwargs: Any) -> ValidationResult:
    """Convenience function to validate markdown content.

    Args:
        content: Markdown content to validate.
        **kwargs: Arguments passed to MarkdownValidator.

    Returns:
        ValidationResult with issues and optionally fixed content.
    """
    validator = MarkdownValidator(**kwargs)
    return validator.validate(content)
