-- migration: 20260620_011_synthea_payers
-- layer: bronze  table: unity.bronze.synthea_payers
-- ${PATIENT360_WAREHOUSE_ROOT} is substituted by ddl-apply.sh before beeline -f.
-- rollback: DROP TABLE IF EXISTS unity.bronze.synthea_payers

CREATE TABLE IF NOT EXISTS unity.bronze.synthea_payers (
    Id STRING,
    NAME STRING,
    OWNERSHIP STRING,
    ADDRESS STRING,
    CITY STRING,
    STATE_HEADQUARTERED STRING,
    ZIP STRING,
    PHONE STRING,
    AMOUNT_COVERED DOUBLE,
    AMOUNT_UNCOVERED DOUBLE,
    REVENUE DOUBLE,
    COVERED_ENCOUNTERS BIGINT,
    UNCOVERED_ENCOUNTERS BIGINT,
    COVERED_MEDICATIONS BIGINT,
    UNCOVERED_MEDICATIONS BIGINT,
    COVERED_PROCEDURES BIGINT,
    UNCOVERED_PROCEDURES BIGINT,
    COVERED_IMMUNIZATIONS BIGINT,
    UNCOVERED_IMMUNIZATIONS BIGINT,
    UNIQUE_CUSTOMERS BIGINT,
    QOLS_AVG DOUBLE,
    MEMBER_MONTHS BIGINT,
    ds DATE NOT NULL,
    _ingested_at TIMESTAMP NOT NULL,
    _source_batch_id STRING NOT NULL,
    _source_file STRING
) USING DELTA
PARTITIONED BY (ds)
LOCATION '${PATIENT360_WAREHOUSE_ROOT}/dev/bronze/synthea_payers'
